# Generated by Django 4.0.6 on 2022-07-31 06:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(upload_to='')),
                ('receipt_date', models.DateTimeField(default=datetime.datetime.now)),
                ('total_amount', models.PositiveIntegerField()),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_transaction', to='wallet.transaction')),
            ],
        ),
    ]
