# Generated by Django 4.0.6 on 2022-07-31 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='signature',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.PositiveSmallIntegerField()),
                ('date_time', models.DateField(blank=True, null=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_reward', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('borrow_date_and_time', models.DateTimeField(default='')),
                ('interest_rate', models.PositiveIntegerField()),
                ('payment_due_date', models.DateTimeField(blank=True, null=True)),
                ('loan_balance', models.PositiveIntegerField()),
                ('loan_term', models.TextField()),
                ('loan_status', models.CharField(default='Unpaid', max_length=15, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_loan', to='wallet.customer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_loan', to='wallet.wallet')),
            ],
        ),
    ]
