# Generated by Django 4.0.6 on 2022-07-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_customer_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pin', models.IntegerField()),
                ('isActive', models.BooleanField(default=False)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
