# Generated by Django 4.0.6 on 2022-07-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.CharField(max_length=15),
        ),
    ]
