# Generated by Django 4.0.6 on 2022-07-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_wallet_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.customer'),
        ),
    ]
