# Generated by Django 4.0.6 on 2022-07-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='customer',
        ),
    ]
