# Generated by Django 4.0.6 on 2022-07-29 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_wallet_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.customer'),
        ),
    ]
