# Generated by Django 4.0.6 on 2022-07-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_wallet_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='employment_status',
            field=models.BooleanField(default=False),
        ),
    ]
