# Generated by Django 4.0.6 on 2022-07-29 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_wallet_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accType', models.CharField(blank=True, max_length=255)),
                ('accName', models.CharField(blank=True, max_length=255)),
                ('savings', models.IntegerField()),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.wallet')),
            ],
        ),
    ]
