# Generated by Django 4.0.6 on 2022-07-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='destination',
        ),
    ]
