# Generated by Django 4.0.6 on 2022-07-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_customer_profile_customer_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='marital_status',
            new_name='maritalStatus',
        ),
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='currency',
            field=models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='wallet.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='third_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.thirdparty'),
        ),
    ]
