# Generated by Django 4.0.6 on 2022-07-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_rename_marital_status_customer_maritalstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='wallet',
            new_name='wallet_assigned',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
    ]
