# Generated by Django 4.0.6 on 2022-07-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_rename_wallet_account_wallet_assigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='wallet_assigned',
            new_name='wallet',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.customer'),
        ),
    ]
