# Generated by Django 4.0.6 on 2022-07-30 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_staus',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='card',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.date),
        ),
        migrations.AddField(
            model_name='card',
            name='signature',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
    ]
