# Generated by Django 4.0.6 on 2022-07-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_card_card_staus_card_cvv_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='signature',
        ),
    ]
