# Generated by Django 4.0.6 on 2022-07-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_remove_card_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='signature',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
    ]
