# Generated by Django 4.0.6 on 2022-07-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_card_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='signature',
            new_name='signature_card',
        ),
    ]
