# Generated by Django 4.0.6 on 2022-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_rename_signature_card_signature_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=9999),
        ),
    ]
