# Generated by Django 4.0.6 on 2022-07-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_alter_card_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cvv',
            new_name='security_code',
        ),
    ]
