# Generated by Django 4.0.6 on 2022-07-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_rename_cvv_card_security_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='account',
            new_name='account_card',
        ),
    ]
