# Generated by Django 4.0.6 on 2022-07-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0028_rename_account_card_card_card_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
