# Generated by Django 4.0.6 on 2022-07-30 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0029_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=25)),
                ('card_name', models.CharField(blank=True, max_length=25)),
                ('pin_number', models.CharField(blank=True, max_length=5)),
                ('security_code', models.CharField(blank=True, max_length=5)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('card_staus', models.CharField(blank=True, max_length=6)),
                ('card_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('signature_card', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
    ]
